# -*- coding: utf-8 -*-
"""arr_minimun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""



def minarr(arr):
  min=arr[0]

  for i in range(len(arr)):
     if min>arr[i]:
        min=arr[i]

  return min

arr=[2,3,4,5,1]
print(minarr(arr))

__