# -*- coding: utf-8 -*-
"""deque_using_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""

class deque:
  def __init__(self):
    self.items = []
  def is_empty(self):
    return len(self.items == 0 )

  def add_front(self,data):
    self.items.insert(-1,data)

  def add_rear(self,data):
    self.items.insert(0,data)

  def get_front(self):
    return self.items[-1]

  def get_rear(self):
    return self.items[0]

  def remove_front(self):
    return self.items.pop(-1)

  def remove_rear(self):
    return self.items.pop(0)

  def size(self):
    return len(self.items)

items=deque()
items.add_front(1)
items.add_rear(2)
items.add_front(3)
items.add_rear(4)
print(items.items)

__