# -*- coding: utf-8 -*-
"""level_traversal_susing_queque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def levelOrder(root):
    if not root:
        return []
    result, queue = [], deque([root])
    while queue:
        level = []
        for _ in range(len(queue)):
            node = queue.popleft()
            level.append(node.val)
            if node.left:
                queue.append(node.left)
            if node.right:
                queue.append(node.right)
        result.append(level)
    return result

# -------- Test the function --------



root = TreeNode(1)
root.left = TreeNode(2)
root.right = TreeNode(3)
root.left.left = TreeNode(4)
root.left.right = TreeNode(5)
root.right.right = TreeNode(6)

# Call the levelOrder function
print("Level order traversal:")
print(levelOrder(root))

_