# -*- coding: utf-8 -*-
"""no._of_two,four_vehicles_by_wheels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""



v = 5
w = 6
if (w & 1) == 1 or w < 2 or w <= v:
    print("INVALID INPUT")
else:
    x = ((4 * v) - w) // 2
    print("TW={0} FW={1}".format(x, v - x))

__