# -*- coding: utf-8 -*-
"""second_largest_arr_without_sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""



def second_largest(arr):
    if len(arr) < 2:
        return None  # Not enough elements

    largest = second = float('-inf')

    for num in arr:
        if num > largest:
            second = largest
            largest = num
        elif largest > num > second:
            second = num

    return second if second != float('-inf') else None

__