# -*- coding: utf-8 -*-
"""stack_using_linked_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

def pop(start):
    if start is None:
        return None
    return start.next  # Returns the new start after popping

def peek(start):
    if start:
        print(start.data)
    else:
        print("Stack is empty")

# Create a stack: top -> 2 -> 1
start = Node(2)
start.next = Node(1)

# Pop operation
start = pop(start)

# Peek operation
peek(start)