# -*- coding: utf-8 -*-
"""swaptwoadjacentnodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M6NBA46taya2H5Jb0ig_C96xYE9A1e9
"""

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution:
    def swapPairs(self, head):
        dummy = ListNode(0)
        dummy.next = head
        prev = dummy

        while head and head.next:
            first = head
            second = head.next

            # Swapping
            prev.next = second
            first.next = second.next
            second.next = first

            # Re-positioning prev and head
            prev = first
            head = first.next

        return dummy.next